#:schema node_modules/wrangler/config-schema.json
name = "bevis"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "732af2ecac434e64a4532ed7200ccf08" }
]

[assets]
directory = "./public"
